channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.11
  # Only put dependencies that are NOT available with pip here (e.g. graph-tool)
  # or that enable extra functionality such as GPU/MKL support
